# Generated by Django 4.1.3 on 2022-11-05 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lyric',
            old_name='song_id',
            new_name='song_track_id',
        ),
        migrations.AddField(
            model_name='lyric',
            name='song',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
            preserve_default=False,
        ),
    ]
