# Generated by Django 4.1.3 on 2022-11-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_rename_song_id_lyric_song_track_id_lyric_song'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lyric',
            name='song_track_id',
            field=models.IntegerField(verbose_name=1),
        ),
    ]
